_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: 05d2d6d9-a46f-4f5b-9c29-aa6df6c4afa8
name: 'Hound Ridge'
mail: dweaver@tampabay.rr.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
