<?php

/**
 * @file
 * Install, uninstall and update hooks for Photoswipe module.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function photoswipe_dynamic_caption_install() {
  // Clear the discovery cache, so the captions appear:
  \Drupal::cache('discovery')->deleteAll();
}

/**
 * Implements hook_requirements().
 */
function photoswipe_dynamic_caption_requirements($phase) {
  // If we are not in runtime phase, there is nothing to do. So bail out early.
  if ($phase !== 'runtime') {
    return [];
  }

  $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');

  $is_cdn_enabled = \Drupal::config('photoswipe.settings')->get('enable_cdn');
  $library_dir = $library_file_finder->find('photoswipe-dynamic-caption-plugin');
  $package_json_path = $library_file_finder->find('photoswipe-dynamic-caption-plugin/package.json');

  // We only care about major version:
  $version_required = 1;
  // @todo Currently, this plugin isn't on bower, nor has it a downloadable
  // Github release, see
  // https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/issues/21
  $help_text = t('
  <strong>Composer installation (recommended)</strong></br>
  <ol>
    <li>Enable usage of third-party libraries using composer, see @here for an explanation.</li>
    <li>Require the photoswipe dynamic caption library using "composer require npm-asset/photoswipe-dynamic-caption-plugin:^1"</li>
  </ol>
  <strong>Manual installation</strong>
  <ol>
    <li>Clone the @githubLink</li>
    <li>Place the cloned photoswipe caption directory in the "libraries" directory on your server.</li>
  </ol>',
  [
    '@githubLink' => Link::fromTextAndUrl(t('Photoswipe dynamic caption plugin'), Url::fromUri('https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin'))->toString(),
    '@here' => Link::fromTextAndUrl(t('here'), Url::fromUri('https://www.drupal.org/docs/develop/using-composer/manage-dependencies#third-party-libraries'))->toString(),
  ]);

  // CDN is enabled, return early:
  if ($is_cdn_enabled) {
    return [];
  }

  // Library directory is empty:
  if (empty($library_dir)) {
    return [
      'photoswipe_dynamic_caption' => [
        'title' => t('Photoswipe dynamic caption plugin'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('<strong>Photoswipe dynamic caption plugin library not found, CDN disabled</strong>'),
        'description' => t('You can either enable requiring the library through CDN @here (not recommended) or install it locally, using the following instructions:<br>@help_text',
        [
          '@help_text' => $help_text,
          '@here' => Link::createFromRoute(t('link'), 'photoswipe.settings')->toString(),
        ]),
      ],
    ];
  }

  // Package json could not be found:
  if (empty($package_json_path)) {
    return [
      'photoswipe_dynamic_caption' => [
        'title' => t('Photoswipe dynamic caption plugin'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('<strong>Photoswipe dynamic caption library found, but missing package.json detected!</strong>'),
        'description' => t('Local library folder found, but library seems to be corrupted, please require the photoswipe dynamic caption library correctly:<br>@help_text', ['@help_text' => $help_text]),
      ],
    ];
  }

  // Package json corrupted:
  $package_json = json_decode(file_get_contents($package_json_path) ?: '{}', TRUE) ?: [];
  $package_json_version = $package_json['version'] ?? NULL;
  if (empty($package_json_version)) {
    return [
      'photoswipe_dynamic_caption' => [
        'title' => t('Photoswipe dynamic caption plugin'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('<strong>Photoswipe dynamic caption library found, but the package.json is corrupted!</strong>'),
        'description' => t('Local library folder found, but library seems to be corrupted, please require the photoswipe dynamic caption library correctly:<br>@help_text', ['@help_text' => $help_text]),
      ],
    ];
  }

  // Version not compatible:
  [$major] = explode('.', $package_json['version'] ?? '');
  if ((int) $major !== $version_required) {
    return [
      'photoswipe_dynamic_caption' => [
        'title' => t('Photoswipe dynamic caption plugin'),
        'severity' => REQUIREMENT_ERROR,
        'value' => t('Current version supports ^@version.x: Please install appropriate version', [
          '@version' => $version_required,
        ]),
        'description' => t('<strong>You need to install a compatible version!</strong><br><br>@help_text', ['@help_text' => $help_text]),
      ],
    ];
  }

  // This should never be reached. Still return an empty array, just in case:
  return [];
}

/**
 * Sets the "photoswipe_dynamic_caption" default options.
 *
 * In some cases, these settings where NULL on sites migrating from photoswipe
 * v4.
 */
function photoswipe_dynamic_caption_update_9001() {
  $configFactory = Drupal::configFactory();
  $config = $configFactory->getEditable('photoswipe_dynamic_caption.settings');
  if (empty($config->get('options.type'))) {
    $config->set('options.type', 'auto');
  }
  if (empty($config->get('options.mobileLayoutBreakpoint'))) {
    $config->set('options.mobileLayoutBreakpoint', 600);
  }
  if (empty($config->get('options.horizontalEdgeThreshold'))) {
    $config->set('options.horizontalEdgeThreshold', 20);
  }
  if (empty($config->get('options.mobileCaptionOverlapRatio'))) {
    $config->set('options.mobileCaptionOverlapRatio', 0.3);
  }
  if (empty($config->get('options.verticallyCenterImage'))) {
    $config->set('options.verticallyCenterImage', FALSE);
  }
  $config->save();
}
